frontend:
  service:
    port: 3000
    image:
      name: iraalf/frontend-service
      version: latest
    ingress:
      enabled: true
      path: /
      pathType: Prefix
statistics:
  service:
    port: 8030
    image:
      name: iraalf/statistics-service
      version: latest
identity-provider:
  service:
    port: 8040
    image:
      name: iraalf/identity-provider-service
      version: latest
privileges:
  service:
    port: 8050
    image:
      name: iraalf/privileges-service
      version: latest
    database:
      name: privileges
flights:
  service:
    port: 8060
    image:
      name: iraalf/flights-service
      version: latest
    database:
      name: flights
tickets:
  service:
    port: 8070
    image:
      name: iraalf/tickets-service
      version: latest
    database:
      name: tickets
gateway:
  service:
    port: 8080
    image:
      name: iraalf/gateway-service
      version: latest
    ingress:
      enabled: true
      path: /api/
      pathType: Prefix
